name: Release VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  release-extension:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install Dependencies
      run: npm install

    - name: Install `vsce`
      run: npm install -g @vscode/vsce

    - name: Get Latest Release Tag
      id: get_latest_release
      run: |
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "v0.0.0")
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Determine Next Version
      id: next_version
      run: |
        IFS='.' read -r major minor patch <<< "${LATEST_TAG#v}"
        patch=$((patch + 1))
        next_version="v$major.$minor.$patch"
        echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

    - name: Package VS Code Extension
      run: |
        vsce package
        mv *.vsix xenon-${{ env.NEXT_VERSION }}.vsix

    - name: Publish release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          gh release create ${{ env.NEXT_VERSION }}                             \
                            --repo="${{ github.repository }}"                   \
                            --title "${{ github.event.pull_request.title }}"    \
                            --generate-notes                                    \
                            *.vsix